### ISSUE TITLE
Not working for CubeCraft

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#10]
The proxy isn't working for CubeCraft `mco.cubecraft.net:19132`. No idea what the problem is this time, it just won't spawn the player. PlayStatusLoginSuccess is received so must be happening after that i guess

**Comment by gioiann** [comment]
ResourcePackStack is also received

**Comment by Sandertv** [comment]
CubeCraft for some reason doesn't acknowledge the ResourcePackClientResponse packet sent by gophertunnel. I'm looking into it.

**Comment by Sandertv** [comment]
Looks like it's fixed in that commit (with a completely messed up git username, whoops). Please give it a try.
