### ISSUE TITLE
Issue connecting to Dragonfly servers

### ISSUE THREAD

**Issue by Prim69** [Sandertv/gophertunnel#119]
When connecting to a Dragonfly server your CPU usage will jump to 100% and your whole PC starts lagging!
There will also be no chunks loaded, you're just sitting in space.

![image](https://user-images.githubusercontent.com/13991048/151681958-f86c6aae-5ca4-4433-ae69-848c64aa5137.png)

**Comment by JustTalDevelops** [comment]
Is there any chance you can try this on a regular Gophertunnel listener and see if the same happens, perhaps the example listener? (still through your proxy)

**Comment by JustTalDevelops** [comment]
Any update on this?

**Comment by Prim69** [comment]
Sorry yea, the same thing happened with the example listener

**Comment by lactyy** [comment]
Hello! I had the same issue, this can be solved by setting EnableClientCache to true in Dialer used for server connection.

**Comment by Prim69** [comment]
> Hello! I had the same issue, this can be solved by setting EnableClientCache to true in Dialer used for server connection.

Thanks!

**Comment by Sandertv** [comment]
Going to reopen this because I'm not actually sure why this happens. It should allow connecting eithout client cachr.
