### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#12]
Currently Raknet handles latency measurements. This doesn't allow the server to measure the full Client/Server latency but only the Server/Proxy latency. I think a way for ConnectedPings and ConnectedPongs to pass through the proxy should be implemented

**Comment by Sandertv** [comment]
Allowing ConnectedPings and ConnectedPongs to pass through would mean that many internals of go-raknet have to be exposed, while I want to keep it as minimalistic as possible. Client-Server latency can be measured by the proxy itself, which should, most of the time, suffice.
