### ISSUE TITLE
Feature for device os

### ISSUE THREAD

**Issue by Arcoz0308** [Sandertv/gophertunnel#127]
add comments to with full name and maybe used devise (for exemple Orbis = playstation)

**Comment by Sandertv** [comment]
Could you explain more thoroughly what you mean?

**Comment by Arcoz0308** [comment]
so, explain for each const what os that is (not only abbreviation), exemole say that WP is for Windows phone, Orbis is for PlayStation ...

**Comment by Sandertv** [comment]
Please feel free to open a PR with any additional information you think is relevant to add to these constants.
