### ISSUE TITLE
Client not properly disconnected

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#13]
If the server sends a Disconnect packet before the ResourcePackStack (which is when the client is considered connected) the client won't get properly disconnected (the Disconnect packet is not sent to the client) and gophertunnel crashes.

**Comment by Sandertv** [comment]
gophertunnel crashes? Could you show the logs for that?

**Comment by gioiann** [comment]
```
2019/08/02 21:09:36 error: Disconnected: Test disconnecting before connected
2019/08/02 21:09:36 error reading from UDP connection (rakAddr = <nil>): read udp [::]:19132: use of closed network connection
panic: connection timeout
```

**Comment by gioiann** [comment]
And the client will keep waiting in the "locating server screen" for a few seconds until it timesout.

**Comment by Sandertv** [comment]
Should be fixed on https://github.com/Sandertv/gophertunnel/commit/18f5ffec58d01e9013a1c45b3dbc40236fcaffa2

**Comment by Sandertv** [comment]
Not quite fixed yet, there's still circumstances under which it will not work correctly.

**Comment by Sandertv** [comment]
Going to close this as there is no perfect way to handle this for the example program.
