### ISSUE TITLE
Gophertunnel doesn't send the correct client's chunk radius

### ISSUE THREAD

**Issue by UnknownOre** [Sandertv/gophertunnel#139]
Gophertunnel would request 16 chunk radius from the server when its doing the login-sequence, which would cause chunks not loading if the client chunks set to under 16

**Comment by Sandertv** [comment]
Closing this. The server-client mismatch is fixed now. In a proxy setting gophertunnel still doesn't properly respect the client's preferred chunk radius, but that is difficult due to gophertunnel's structure and isn't nearly as big of an issue.
