### ISSUE TITLE
Xbox live login fails

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#14]
`panic: error obtaining Live token: error decoding flowtoken XML container: EOF`

This error started happening really often, then it went away and now it seems like it happens everytime.

I tried with different accounts and also different IPs in case Microsoft blocked my IP because of suspicious login attempts.
I also tried creating a new account using a new residential IP and then use the same IP to login with gophertunnel API, it's not working, same error but I'm able to login using minecraft

**Comment by Sandertv** [comment]
Had some reports of this. Probably some Microsoft account login changes. I'll fix it when I get the time.

**Comment by gioiann** [comment]
I would like to help but there are is no documentation from Microsoft about the Minecraft login flow. I tried using an https proxy but apparently Minecraft doesn't trust the proxy CA. How did you do it?

**Comment by Sandertv** [comment]
There's some libraries in other languages that implement Microsoft account logins: Looking into those would be worth it.

**Comment by gioiann** [comment]
Can you give me an hint about where to start? Like, what libraries are you talking about? I don't think there is a library implementing LoginPacket signing. The only way would be reverse engineering Minecraft or an https proxy

**Comment by Sandertv** [comment]
The only thing that needs to be done is to login to a Live/Microsoft account and obtain an access token and a refresh token. The rest will still function just fine. Basically, the code in auth/live.go needs to be replaced.

**Comment by Sandertv** [comment]
This part has nothing to do with Minecraft yet.

**Comment by gioiann** [comment]
I found the problem: parseJSObject() doesn't properly parse the data. There are closing curly brackets before the end of the object properties.

**Comment by gioiann** [comment]
Not only that, there are different things wrong with parseJSObject() like:
- There can be commas in the value
- " is not trimmed, only ' is

**Comment by Sandertv** [comment]
The parseJSObject is a terrible hack that was only there as some kind of hack. The login sequence in live.go is quite the hack.

**Comment by gioiann** [comment]
Should I open a PR ?

**Comment by Sandertv** [comment]
Please feel free!
