### ISSUE TITLE
Packets with unread bytes should be handled

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#17]
On LBSG servers the ResourcePacksInfo is encoded [like that](https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/network/protocol/ResourcePacksInfoPacket.php#L26)

Causing [this error](https://github.com/Sandertv/gophertunnel/blob/fe04e2b9c128b65f4af556d68e53939fbef8d4b0/minecraft/conn.go#L435) which won't allow the packet to be handled:

```
1 unread bytes left in packet *packet.ResourcePacksInfo{TexturePackRequired:false HasScripts:false BehaviourPacks:[] TexturePacks:[]}: 0x00 (full payload: 0x0600000000000000)
```

The client instead doesn't care about unread bytes and works just fine.

I think gophertunnel should behave as close to the Minecraft client as possible so, in case there are unread bytes an error should be printed but the packet should still be handled

To reproduce the error simply join play.lbsg.net:19132 with the proxy

**Comment by Sandertv** [comment]
Fair enough, it should probably handle them yeah. I'll change it in a bit.

**Comment by Sandertv** [comment]
The behaviour was changed in 01f9ef439be04ebf960b0651785a34e11a753731. It now logs a message and continues handling the packet.
