### ISSUE TITLE
Resource pack temp error

### ISSUE THREAD

**Issue by UnknownOre** [Sandertv/gophertunnel#172]
this seems to be an issue after this [commit](https://github.com/Sandertv/gophertunnel/commit/495fad33cba9db9dd856aa4f021abf10e7381030) 
```
panic: error creating temp zip file: open /root/.config/packs/resource_pack-3262936146.mcpack: no such file or directory

**Comment by ItsZodiaX** [comment]
Same error here
`panic: error creating temp zip file: open /home/container/.config/packs/resource_pack-2766335549.mcpack: no such file or directory`
To be more specific, Happen on Linux and works fine on Windows for me

**Comment by UnknownOre** [comment]
it's broken on both linux and windows for me
