### ISSUE TITLE
Gophertunnel crashing when trying to join PowerNukkitX server!

### ISSUE THREAD

**Issue by VinkyV** [Sandertv/gophertunnel#193]
Authenticate at https://www.microsoft.com/link using the code Y4Y8FBVX.
Authentication successful.
2023/08/16 03:49:00 error: packet 11: nbt: unknown tag '125' at offset 3 during op 'Match'
dial minecraft 127.0.0.1:50736->127.0.0.1:19132: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xe37df0]

Gophertunnel proxy crashing when i trying to join PowerNukkitX server.

**Comment by JavierLeon9966** [comment]
It doesn't seem like you sent all the error stack trace

**Comment by VinkyV** [comment]
> It doesn't seem like you sent all the error stack trace

It's enough to resolve a problem, bottom is just a line number with panic func from git cloned main.go

**Comment by Sandertv** [comment]
This is PowerNukkitX sending broken StartGame packets. Please open an issue on their project.
