### ISSUE TITLE
Xbox client spawning issues

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#22]
The following error occurs when using the Minecraft Xbox One edition. I can't reproduce it as I don't have an Xbox One but all you need to do is join gophertunnel and that will happen.

```
panic: start game spawning timeout
```

I guess the client doesn't like the StartGame packet gophertunnel creates.

The Xbox client is able to join other external servers just fine (only tested on PocketMine servers)

**Comment by Sandertv** [comment]
This is going to be a difficult one to debug as I don't have an XBOX One either. I'll get in contact with someone who does. Thanks for reporting the issue.

**Comment by gioiann** [comment]
I usually use different accounts to login on gophertunnel and a different one in the game, never had any problem doing that.

Anyway, in my test the account was the same. It's not a connection problem, the person testing it for me can join all other servers except gophertunnel hosted on a LAN pc.

Probably the server has something to do with it? Try on mineplex (mco.mineplex.com) and the hive (hivebedrock.network) if you can.

I've no other information right now :/

**Comment by Sandertv** [comment]
I've had the person test on the Hive which, according to him, worked, so it's probably something else.
🤔

**Comment by Sandertv** [comment]
This commit https://github.com/Sandertv/gophertunnel/commit/b7be57516036c2604b03ec8a227c39da95169ce6 might fix it. I found out the spawning sequence takes very long under even just a little bit of latency. That commit gives it more time.

**Comment by Sandertv** [comment]
Any update @gioiann?

**Comment by gioiann** [comment]
I'm using an heavely modified version of gophertunnel (I consider a connection to be "logged in" as the login packet is received) and I have no idea if this still occurs for the "original version". Also, I've never reproduced it. Feel free to close

**Comment by Sandertv** [comment]
Got it 👍
