### ISSUE TITLE
Add NBT Network Format Option Transmission to Exclude Root Tag Name from Java Edition 1.20.2 (Protocol 764)

### ISSUE THREAD

**Issue by robinbraemer** [Sandertv/gophertunnel#220]
I'm currently in the process of [upgrading](https://github.com/minekube/gate/pull/258/files) Gate to mc 1.20.3 and wanted to make you aware of yet another breaking change Mojang made since you support BigEndian for Minecraft Java edition this might be interesting for you.

> Since Java Edition 1.20.2 (Protocol 764), NBT sent over the network has been updated to exclude the name from the root TAG_COMPOUND; see the first link.

Like Tnze/go-mc did you could add smth like a `NetworkFormat` option.

**Relevant links:**
- **wiki**: https://wiki.vg/NBT#Network_NBT_.28Java_Edition.29
- **reference implementation**: https://github.com/Tnze/go-mc/commit/7d6e65f554bc283048791817670a3cc115ea6c1e
- velocity: https://github.com/PaperMC/Velocity/blob/00ef92bc5c82c46ed4770aaaf126c285a6ab705c/proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java#L435

**Comment by TwistedAsylumMC** [comment]
Thanks for informing us about this change, would you be able to confirm if https://github.com/Sandertv/gophertunnel/commit/4a326e160abe5faddeb2fdbcb853b3ee0226cb67 covers the change correctly?

**Comment by robinbraemer** [comment]
Yes his lib works, I tested it

**Comment by robinbraemer** [comment]
However, it would be better to make this behavior optional because pre-1.20.2 versions still need the tag name. Gate proxy supports backwards compatibility.

**Comment by TwistedAsylumMC** [comment]
> However, it would be better to make this behavior optional because pre-1.20.2 versions still need the tag name. Gate proxy supports backwards compatibility.

There is still backwards compatability since this is a different type. `nbt.BigEndian` is the pre-1.20.2 version and `nbt.NetworkBigEndian` is the newer version. Since you tested this change, I'll get it merged into the main branch
