### ISSUE TITLE
errors.Is() always returns false with net.OpError from raknet

### ISSUE THREAD

**Issue by Dasciam** [Sandertv/gophertunnel#228]
The problem is in the following code:
https://github.com/Sandertv/gophertunnel/blob/3c4144b2130899ef2249c438540c27908d2f5a37/minecraft/dial.go#L289
https://github.com/Sandertv/gophertunnel/blob/3c4144b2130899ef2249c438540c27908d2f5a37/minecraft/conn.go#L443
https://github.com/Sandertv/gophertunnel/blob/3c4144b2130899ef2249c438540c27908d2f5a37/minecraft/listener.go#L278

Calling errors.Is() always returns false, because of this, panic is spawned every time a player leaves the server

**Comment by Sandertv** [comment]
Could you try commit 7270e9e and see if this still happens?

**Comment by Dasciam** [comment]
Issue still exists

**Comment by Dasciam** [comment]
All works good. Sorry for misleading...
