### ISSUE TITLE
Stopped working in the lastest 1.13.0

### ISSUE THREAD

**Issue by TheGrandPew** [Sandertv/gophertunnel#23]
I was getting errors about the protocol version, though i just changed it. Now im getting 

`2019/11/01 19:25:22 error: error decoding login request: original raw token payload is not equal to the parsed data:
        payload: {"AnimatedImageData":[{"Frames":2.0,"Image":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

**Comment by Sandertv** [comment]
Gophertunnel was just updated to 1.13. Please update it to the latest version.

**Comment by TheGrandPew** [comment]
> Gophertunnel was just updated to 1.13. Please update it to the latest version.

A cool thanks btw its a really cool project

**Comment by TheGrandPew** [comment]
Hey I didn't want to open a new issue for the sake of connivance, but i'm getting new errors `2019/11/02 09:55:44 1 unread bytes left in packet *packet.MoveActorDelta{EntityRuntimeID:193 DeltaPosition:[0 0 0] DeltaRotation:[0 0 357.1875]} from [209]: 0x3132372e302e302e313a3139313332 (full payload: 0x6fc10160fed1)` and its constantly occurring.

**Comment by Sandertv** [comment]
Please check the latest commit. I've just fixed it.
