### ISSUE TITLE
GUIScale can also be -2

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#3]
[This](https://github.com/Sandertv/gophertunnel/blob/6756c51f8ca7965b8b73be302800cf46f67e09fa/minecraft/protocol/login/data.go#L145) is simply wrong, I can set the GUIScale to -2 in the minecraft settings

**Comment by Sandertv** [comment]
Thanks for mentioning. What device are you on?

**Comment by gioiann** [comment]
Oneplus 5

**Comment by gioiann** [comment]
![Screenshot_20190624-190652](https://user-images.githubusercontent.com/32357209/60038079-92ef9d00-96b3-11e9-8d7c-748f620665fe.jpg)

And if i do set it to -2 the proxy just crashes because of that

**Comment by Sandertv** [comment]
Latest commit addresses it.
