### ISSUE TITLE
Any way to use the auth package to generate the service token needed for the pocket realms api?

### ISSUE THREAD

**Issue by unlimitedcoder2** [Sandertv/gophertunnel#30]
I was wondering if there was any way to generate the XBL3.0 Service token that is needed to call the pocket realms api as described in [this](https://wiki.vg/Pocket_Realms) ?

**Comment by Sandertv** [comment]
Yes, that should be possible. If you have a look here, it creates the same header as required for that: https://github.com/Sandertv/gophertunnel/blob/master/minecraft/auth/minecraft.go#L32. You will have to obtain an XSTS token, for which you can find code if you have a look through how it's used in the proxy. The line I linked shows what data you need from that token and how to format it.

**Comment by unlimitedcoder2** [comment]
I have just done that however, when I try to send the request it says unauthorized. [Image](https://totallynotavir.us/i/rkva.png)

**Comment by Sandertv** [comment]
When you tried this, did you use the RequestXSTSToken function or the RequestXSTSTokenUserOnly function?

**Comment by unlimitedcoder2** [comment]
```go
tp, err := auth.RequestLiveToken("email", "password")

if err != nil {
	fmt.Println(err)
	return
}

xs, err := auth.RequestXSTSToken(tp)

if err != nil {
	fmt.Println(err)
	return
}

fmt.Printf("XBL3.0 x=%v;%v", xs.DisplayClaims.XUI[0].UserHash, xs.Token)
``` This is the code I have it calls `RequestXSTSToken `

**Comment by Sandertv** [comment]
Now that I think of it, realms probably need a different `RelyingParty`

**Comment by unlimitedcoder2** [comment]
Ok

**Comment by Sandertv** [comment]
With the latest commit of gophertunnel, the following works:
```go
	token, _ := auth.RequestLiveToken()
	xbl, _ := auth.RequestXBLToken(token, "https://pocket.realms.minecraft.net/")

	req, _ := http.NewRequest("GET", "https://pocket.realms.minecraft.net/worlds", bytes.NewReader(nil))
	xbl.SetAuthHeader(req)
	req.Header.Set("User-Agent", "MCPE/Android")
	req.Header.Set("Client-Version", protocol.CurrentVersion)

	resp, _ := (&http.Client{}).Do(req)
	b, _ := ioutil.ReadAll(resp.Body)
	fmt.Println(string(b)) // {"servers":[]}
```
Please let me know if you can get it to work like this. If that works, I'll close the issue.
