### ISSUE TITLE
Description Request

### ISSUE THREAD

**Issue by bundabrg** [Sandertv/gophertunnel#35]
Hi There,

I'm working on [NukkitX Protocol](https://github.com/NukkitX/Protocol/pull/47).  You have some great comments for your structs and I wanted to check if you minded if I use some of them whilst I put together the new classes for 1.16.

Thanks

**Comment by Sandertv** [comment]
Hello,

Please feel very free to take anything from gophertunnel that might be useful to you.

**Comment by bundabrg** [comment]
Thank-you very much.
