### ISSUE TITLE
ClientData validation fails if SkinGeometry is empty

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#5]
Some skins can have an empty Geometry. I found out randomly by using the "Ocean Explorer James" skin from the "Deep Sea Mash-up Skin Pack", using this skin will result in the valudation to fail because it has no geometry (empty string)
I don't know about other skins, only tested with this one.

![skin](https://user-images.githubusercontent.com/32357209/60894096-577fd180-a262-11e9-8ab8-a33992bc96a9.png)

That's the error:

`invalid client data: SkinGeometry base64 decoded was not a valid JSON string: unexpected end of JSON input`

**Comment by Sandertv** [comment]
Someone else ran into this error too, but I had not yet realised it had to do with empty geometry data. Thanks.

**Comment by Sandertv** [comment]
Fixed by 5023a919b05f06138a26629882ae9c98cf26b4e1.
