### ISSUE TITLE
Kick on login in server

### ISSUE THREAD

**Issue by Inaayat04** [Sandertv/gophertunnel#56]
I keep getting this error when I join a server and it kicks me 

2021/02/12 16:44:19 error: parse login request: validate token 2: square/go-jose/jwt: validation field, token issued in the future (iat)

How to fix that?

**Comment by TwistedAsylumMC** [comment]
Does this happen with every server you join? Or is it a specific server only. If it's a specific server, please give the IP address so we can try to reproduce the error

**Comment by Inaayat04** [comment]
It happens on every server I join.

**Comment by Sandertv** [comment]
This has to do with your system's time not being set correctly. Unfortunately there's nothing I can do about that. Try checking your time and correcting it where appropriate.
