### ISSUE TITLE
minecraft.Conn: Memory leak (objects are never freed)

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#7]
![mem](https://user-images.githubusercontent.com/32357209/60904140-d1b85200-a272-11e9-9e5b-124e1f8d2361.png)

When I first join the proxy the memory will raise and stop at about 30MB but if I keep joining the used memory will increase about 5 or 10 MB everytime i join. So, by joining like 10 times it reached 80MB and it will keep increasing if I keep joining.

This is without lua. I think 80MB or even 30MB is a lot for a proxy which does nothing but forward packets.

Does the proxy keep chunks, skins, resource packs ?

**Comment by Sandertv** [comment]
5-10MB per connection is to be expected. It caches used memory so that it doesn't have to re-allocate every time for packet reading. If it isn't deallocated though, there might indeed be a leak present. I'll get to debugging it.

**Comment by Sandertv** [comment]
Fixed by 17f17caace1b6a28040f242f494948e11bca176f.

**Comment by gioiann** [comment]
@Sandertv Did you test? It's still happening for me

**Comment by Sandertv** [comment]
It sounds to me like the garbage collector doesn't deem it necessary to run yet. There were actually (multiple) memory leaks, but those were resolved in the commit above.
