### ISSUE TITLE
Can't connect to localhost game

### ISSUE THREAD

**Issue by sermah** [Sandertv/gophertunnel#73]
I can't connect to my **localhost world** using `Dial("raknet", "localhost:19132")` function. It says
```
panic: ping raknet: context deadline exceeded
```
What I've tried already (and it didn't work):
- `127.0.0.1`, `[::1]`
- setting `udp` and `tcp` instead of `raknet` (`udp` makes it wait until `context deadline exceeded`, `tcp` connection was just refused)
- using `DialTimeout(...)` set to several minutes

I didn't change anything in the firewall settings, I have Windows 10 and LAN Multiplayer option is turned on in my world.
**Everything works fine when I join some internet server.** Am I missing something?

**Comment by Sandertv** [comment]
Hi! There's two things that seem to be like they might be the issue. First, do you know if the correct port is actually 19132? Can you verify that somehow? Second, you might have to set loopback exemptions for Minecraft using the following command: `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"`

Please let me know if you get anything with either of those.

**Comment by sermah** [comment]
> First, do you know if the correct port is actually 19132? Can you verify that somehow?

Actually I am not sure. Several sites say it's the default port. 
Any ideas how to check which port should I connect to?

**Comment by Sandertv** [comment]
Unknown if this is a bug in gophertunnel or something else affecting it. Apparently connecting through gophertunnel with a different device is possible.

**Comment by sermah** [comment]
I tried launching gophertunnel and BDS on the same machine and gt successfully joined the game.
So, this bug affects only worlds launched in MCBE game.

**Comment by JustTalDevelops** [comment]
The default port for servers is 19132, but the client-ran server seems to be a random port. You should try using Wireshark to figure out the actual port.

**Comment by TwistedAsylumMC** [comment]
Like Tal said, client servers choose random ports however they do also broadcast to 19132 to allow for the servers to show on LAN, and go-raknet supports the following of the broadcasts. The issue you're facing is actually the fact that the client server does not accept connections from the same device it is running on.

**Comment by Sandertv** [comment]
Going to close this for the reasons mentioned above.
