### ISSUE TITLE
Enchanted books broken when passing through gophertunnel

### ISSUE THREAD

**Issue by racerxdl** [Sandertv/gophertunnel#87]
When getting enchanted books from the villager, the enchanted books comes fine, but if you drop it or relog into the game, the enchantments disappear. That only happens when cheats enabled = false, if its true, it works fine.

To be better clarify the issue, I added a video.

https://user-images.githubusercontent.com/578310/124321642-70bb7000-db54-11eb-8e9c-8fb147aad516.mp4

Steps to simulate:

- Create new world in Bedrock Server
- Add a villager, lectern and bed. Get some emerald and books
- Switch to survivavel and disable cheats in server.properties
- Trade with the villager for a enchanted book
- Relog / drop the item

**Comment by racerxdl** [comment]
Investigating a little further, the problem is on `ItemStackRequest` packet.

**Comment by Sandertv** [comment]
Should be fixed by https://github.com/Sandertv/gophertunnel/commit/1734b6a36b5916ebcf33be5ec9e8676184ff9d44.
