### ISSUE TITLE
NewIncomingConnection + ping (client)

### ISSUE THREAD

**Issue by fwflunky** [Sandertv/gophertunnel#98]
Hello, I noticed that the NewIncomingConnection is sent along with the ping inside encapsulated packet. Please add the ping packet sending along with the NewIncomingConnection
![image](https://user-images.githubusercontent.com/38854160/131516111-c127b475-d41f-4487-b544-383f61945e11.png)

**Comment by Sandertv** [comment]
Why?

**Comment by fwflunky** [comment]
> Why?

The server can check for a ping packet with a NewIncomingConnection in the same encapsulated packet, then filter the bot. I think you need to make a bypass (sorry for my bad english)

**Comment by Sandertv** [comment]
Nobody would ever use this to check against gophertunnel because nothing prevents the mcpe client from doing this. I suppose it can be changed but it is in no way a concern. People checking against this would just be shooting their own foot

**Comment by Sandertv** [comment]
> I suppose it can be changed
No need to close this. If anyone feels like changing it' it'll be changed.

**Comment by Sandertv** [comment]
Sorry for the snappy answers earlier, that wasn't very cool.
