### ISSUE TITLE
Add Ratelimit for serverlist ping

### ISSUE THREAD

**Issue by vanlueckn** [Sandertv/gophertunnel#99]
Ratelimit for serverlist ping would be a good enhancement. 

Currently we have to watch for those pacekts manually in got via the raknet package.

**Comment by Sandertv** [comment]
Rate limiting that sounds rather useless. Any client can spoof their IP at any point and send packets with different IPs+ports for every packets.

**Comment by vanlueckn** [comment]
I implemented the rate limit by myself, it is a special use case for one of my projects. I will close this issue.
